# Use YAML Anchors to avoid duplication of value between `airflow.dags.persistence.existingClaim` and `localDags.name`
airflowDagClaimName: &airflowDagClaimName "airflow-dags-folder"

airflow:
  enabled: true

  defaultAirflowTag: "2.10.5"
  airflowVersion: "2.10.5"

  # Fernet key settings
  # Note: fernetKey can only be set during install, not upgrade
  fernetKey: "supersecretfernetkey"

  # Flask secret key for Airflow Webserver: `[webserver] secret_key` in airflow.cfg
  webserverSecretKey: "supersecretwebserversecretkey"

  # Airflow executor
  # One of: LocalExecutor, LocalKubernetesExecutor, CeleryExecutor, KubernetesExecutor, CeleryKubernetesExecutor
  # Specify executors in a prioritized list to leverage multiple execution environments as needed.
  executor: "CeleryExecutor"

  config:
    logging:
      colored_console_log: "True"
    webserver:
      expose_config: "True"

  dags:
    persistence:
      enabled: true

      accessMode: "ReadOnlyMany"
      existingClaim: *airflowDagClaimName

  extraEnv: |
    - name: ENVIRONMENT
      value: "local"

  ingress:
    web:
      enabled: true

      ingressClassName: "nginx"
      path: "/"

localDags:
  enabled: true

  capacity: "1Gi"
  name: *airflowDagClaimName
  pathToDags: ~

nginx:
  enabled: true
