# Use YAML Anchors to avoid duplication of value between `airflow.dags.persistence.existingClaim` and `localDags.name`
airflowDagClaimName: &airflowDagClaimName "airflow-dags-folder"

airflow:
  enabled: true

#  defaultAirflowTag: "2.10.5"
#  airflowVersion: "2.10.5"
  defaultAirflowTag: "3.0.1"
  airflowVersion: "3.0.1"

  # Fernet key settings
  # Note: fernetKey can only be set during install, not upgrade
  fernetKey: "supersecretfernetkey"

  # Flask secret key for Airflow Webserver: `[webserver] secret_key` in airflow.cfg
  webserverSecretKey: "supersecretwebserversecretkey"

  # Airflow executor
  # One of: LocalExecutor, LocalKubernetesExecutor, CeleryExecutor, KubernetesExecutor, CeleryKubernetesExecutor
  # Specify executors in a prioritized list to leverage multiple execution environments as needed.
  executor: "CeleryExecutor"

  config:
    api_auth:
      # 3.0.0-specific
      jwt_secret: "abcdefghijklmnopqrstuvwxyz"
    logging:
      colored_console_log: "True"
    webserver:
      expose_config: "True"

  dags:
    persistence:
      enabled: true

      accessMode: "ReadOnlyMany"
      existingClaim: *airflowDagClaimName

  extraEnv: |
    - name: ENVIRONMENT
      value: "local"

  ingress:
    # TODO: ingress missing for 3.x's api server; waiting for updated chart release
    web:
      enabled: true

      ingressClassName: "nginx"
      path: "/"

  redis:
    # allow redis to be terminated quicker
    terminationGracePeriodSeconds: 30

localDags:
  enabled: true

  capacity: "1Gi"
  name: *airflowDagClaimName
  pathToDags: ~

nginx:
  enabled: true
